#! /bin/sh

pkill -USR1 -x sxhkd || sxhkd &
#test pgrep -x sxhkd > /dev/null

bspc monitor HDMI-0 -d a s d f g
bspc monitor DP-2 -d h j k l z

bspc config border_width          0
bspc config presel_feedback_color \#a55a84
bspc config normal_border_color   \#a55a84
bspc config focused_border_color  \#a55a84
bspc config active_border_color   \#9BA6A4
bspc config window_gap            24
#old color: #080416

bspc config split_ratio           0.52
bspc config top_padding           36
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

wmname dagger-bspwm &

#fix displays
$HOME/.config/xrandr-monitor-fix/launch.sh &

#launch bg (not needed, pywal does it?)
#feh --bg-scale $HOME/pictures/wallpaper/bocchi.jpg &

#launch pywal
(cat ~/.cache/wal/sequences &)
wal -R

#launch picom (screens flip if you don't, also f**** terminal transparency)
picom --backend glx --vsync --corner-radius 15 -c --active-opacity .95 --inactive-opacity .95 --blur-background &

#launch polybar
$HOME/.config/polybar/launch.sh &
