#! /bin/sh

pkill -USR1 -x sxhkd || sxhkd &
#test pgrep -x sxhkd > /dev/null

bspc monitor HDMI-0 -d a s d f g
bspc monitor DP-2 -d h j k l z

bspc config border_width          2
bspc config presel_feedback_color \#080416
bspc config normal_border_color   \#080416
bspc config focused_border_color  \#080416
bspc config active_border_color   \#080416
bspc config window_gap            12

bspc config split_ratio           0.52
bspc config top_padding           28
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

wmname daga-bspwm &

#fix displays
$HOME/.config/xrandr-monitor-fix/launch.sh &

#launch bg
feh --bg-scale $HOME/Pictures/wallpaper/sunset-bg.jpg &

#launch pywal
(cat ~/.cache/wal/sequences &)
wal -R

#launch picom (screens flip if you don't, also f**** terminal transparency)
picom -b --backend glx --vsync --corner-radius 15 &

#launch polybar
$HOME/.config/polybar/launch.sh &