#! /bin/sh

pkill -USR1 -x sxhkd || sxhkd &
#test 
#test pgrep -x sxhkd > /dev/null

bspc monitor HDMI-1 -d a s d f g
bspc monitor DP-2 -d h j k l z

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#fix displays
$HOME/.config/xrandr-monitor-fix/launch.sh

#launch bg
feh --bg-scale /home/ryan/Pictures/wallpaper/sunset-bg.jpg

#launch compton (screens flip if you don't, also f**** terminal transparency)
compton --backend glx --vsync opengl-swc

#launch pywal
(cat ~/.cache/wal/sequences &)
wal -R

#launch polybar
$HOME/.config/polybar/launch.sh

echo "bspwm booted"